apiVersion: v1
kind: Pod
metadata:
  name: conversao-moedas
spec:
  containers:
  - name: cotacoes
    image: averaacademy/kubernetes:conversao-moedas
    volumeMounts:
    - name: config-volume
      mountPath: /app/config
      readOnly: true
  volumes:
  - name: config-volume
    secret:
      secretName: cotacoes-secret
