apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  labels:
    app: load-test
spec:
  type: NodePort
  selector:
    app: load-test
  ports:
    - name: load-test
      protocol: TCP
      port: 80
      targetPort: load-test
      nodePort: 30555
    - name: whoami
      protocol: TCP
      port: 4200
      targetPort: whoami
      nodePort: 30556
