apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    app: load-test
spec:
  progressDeadlineSeconds: 20
  replicas: 1
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - name: load-test
        image: averaacademy/kubernetes:load-test
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        ports:
        - containerPort: 8080
          name: load-test
        resources:
          requests:
            cpu: 200m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 500Mi
      - name: whoami
        image: containous/whoami
        ports:
        - containerPort: 80
          name: whoami
