apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  labels:
    app: load-test
spec:
  selector:
    app: load-test
  ports:
    - name: load-test
      protocol: TCP
      port: 80
      targetPort: load-test
