apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: node-selector-demo
  template:
    metadata:
      labels:
        run: node-selector-demo
    spec:
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        diskType: SSD
        cpuType: arm
