apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-site
spec:
  rules:
  - host: kubernetes.averaacademy
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-site-service
            port:
              number: 80
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: kubernetes-site-service
            port:
              number: 4200
      - path: /load-test
        pathType: Prefix
        backend:
          service:
            name: kubernetes-site-service
            port:
              number: 4200
