apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-site
spec:
  rules:
  - host: kubernetes.averaacademy
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-site-service
            port:
              number: 80
      - path: /swagger
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-site-service
            port:
              number: 4200
