apiVersion: v1
kind: Pod
metadata:
  name: cm-envvar
spec:
  containers:
  - name: envvar
    image: averaacademy/kubernetes:environment-variables
    env:
    - name: VARIABLE1
      valueFrom:
        configMapKeyRef:
          name: envvars
          key: VAR1
    envFrom:
    - configMapRef:
        name: cotacoes

