apiVersion: v1
kind: Service
metadata:
  name: load-test-service-headless
  labels:
    app: load-test-headless
spec:
  clusterIP: None
  selector:
    app: load-test
  ports:
    - name: load-test
      protocol: TCP
      port: 80
      targetPort: load-test
    - name: whoami
      protocol: TCP
      port: 4200
      targetPort: whoami
