apiVersion: v1
kind: Service
metadata:
  name: site-estatico
spec:
  selector:
    app: site-estatico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-estatico
spec:
  rules:
  - host: kubernetes-site.averaacademy
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: site-estatico
            port:
              number: 80